Repository projectceladon/manifest, pull requests merged in 2022-08, with the labels that each got.

#287 Manifest upgraded to Android T android-13.0.0_r1
  default.xml
  include/aosp_vanilla.xml
  include/bsp-celadon.xml
Labels: PR approved, Valid commit message

#283 Update Weekly External Release manifest
  stable-build/CIV_00.22.03.34_A13.xml
  stable-build/latest.xml
Labels: Invalid commit message

#288 Update Weekly External Release manifest
  stable-build/CIV_01.22.03.32_A12.xml
  stable-build/latest.xml
Labels: Invalid commit message, PR approved
