Repository projectceladon/manifest, pull requests merged in 2022-11, with the labels that each got.

#300 Update kernel revision to CFI enabled tag
  include/bsp-celadon.xml
Labels: PR approved, Valid commit message

#301 AOSP rebase to android-13.0.0_r12
  default.xml
  include/aosp_vanilla.xml
Labels: Valid commit message

#302 update manifest for kernel-5.15.74 rebase
  include/bsp-celadon.xml
Labels: Invalid commit message, PR approved

#304 Change branch to main for linux-intel-lts2021-chromium
  include/bsp-celadon.xml
Labels: PR approved, Valid commit message

#305 Checking out clipboard-agent to vendor/intel/external
  include/bsp-celadon.xml
Labels: PR approved

#296 Update Weekly External Release manifest
  stable-build/CIV_03.22.03.37_A11.xml
  stable-build/latest.xml
Labels: Invalid commit message, PR approved

#306 Remove not supported kernels
  include/bsp-celadon.xml
Labels: Valid commit message
